baseURL: "https://arkalim.org"
languageCode: en-us
title: Omar Ebrahim
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects
      weight: 20
    - identifier: search
      name: Search
      url: /search
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags
      weight: 40

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Omar Ebrahim"
    subtitle: Experienced DevOps engineer with a passion for streamlining development, deployment, and operations processes. Adept at combining technical expertise with strong communication skills to bridge the gap between development and IT operations teams. Proven track record of implementing robust CI/CD pipelines, infrastructure automation, and cloud solutions that enhance productivity and reliability. Dedicated to fostering a culture of collaboration, continuous improvement, and agile methodologies to drive software delivery excellence.
    imageUrl: "home/Omar-Ebrahim.jpg"
    imageWidth: 220
    imageHeight: 220

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:ebrahimo@uwindsor.ca"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/omar-ebrahim"
    - name: "github"
      url: "https://github.com/Omar-Ebrahim-1"
    - name: "cv"
      url: "https://example.com"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
